"""Phase 10: render README.md from README.template.md, with every number read from results/.

The template is hand-written prose with placeholders:
  {{name}}        a single value (see build_values), e.g. {{test.two_stage.ndcg}}
  {{table:name}}  a whole markdown table (see build_tables), e.g. {{table:headline}}
An unknown placeholder is an error, never a blank. Only committed files are read (results/*.csv),
so `--check` works in CI without the dataset.

  python -m scripts.write_readme           write README.md
  python -m scripts.write_readme --check   exit 1 (with a diff) if README.md is stale
"""
import argparse
import difflib
import json
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
TEMPLATE = ROOT / "README.template.md"
README = ROOT / "README.md"
HEADER = ("<!-- Generated by scripts/write_readme.py from README.template.md and results/*.csv.\n"
          "     Edit the template, then run `make readme`. `make readme-check` (also in CI) fails\n"
          "     if this file and the results disagree. -->\n")
PLACEHOLDER = re.compile(r"\{\{\s*([A-Za-z0-9_.:@\-]+)\s*\}\}")

NAMES = {"most_popular": "Most-popular", "item_knn": "Item-kNN", "implicit_als": "Implicit ALS",
         "ease": "EASE", "ease_recent": "EASE, recent-10 input (control)",
         "two_tower": "Two-tower (retrieval)", "two_stage": "**Two-stage (headline)**",
         "two_stage_no_ease": "Two-stage without EASE features (ablation)",
         "two_stage_with_time": "Two-stage + time features (ablation, not used)"}


def f3(x):
    return f"{x:.3f}"


def f4(x):
    return f"{x:.4f}"


def pct(x, d=1):
    return f"{100 * x:.{d}f}%"


def sgn(x, d=4):
    return f"{x:+.{d}f}"


def load(name):
    return pd.read_csv(RESULTS / name)


def stat_table(name):
    d = load(name)
    return {(r.scheme, r.stat): r.value for r in d.itertuples()}


# ---------------------------------------------------------------------------------------------
# Values
# ---------------------------------------------------------------------------------------------

def build_values():
    v = {}
    ds = stat_table("data_stats.csv")
    num = lambda k: float(ds[k])
    v["data.ratings"] = f"{int(num(('all', 'ratings_total'))):,}"
    v["data.users"] = f"{int(num(('user', 'users_total'))):,}"
    v["data.movies"] = f"{int(num(('all', 'movies_total'))):,}"
    v["data.movies_rated"] = f"{int(num(('all', 'movies_rated'))):,}"
    v["data.movies_train"] = f"{int(num(('all', 'movies_with_train_rating'))):,}"
    v["data.movies_cold"] = f"{int(num(('all', 'movies_only_in_val_or_test'))):,}"
    v["data.movies_genome"] = f"{int(num(('all', 'movies_with_genome'))):,}"
    v["data.burst_1h"] = pct(num(("user", "test_span_le_1h_share")))
    v["data.burst_median_min"] = f"{60 * num(('user', 'test_span_median_hours')):.0f}"
    v["data.cut_same_second"] = f"{int(num(('user', 'users_train_val_cut_within_same_second'))):,}"
    v["data.cut_1h"] = pct(num(("user", "users_train_val_cut_within_1h_share")))
    v["data.val_users"] = f"{int(num(('user', 'users_eligible_with_val_positive'))):,}"
    v["data.test_users"] = f"{int(num(('user', 'users_eligible_with_test_positive'))):,}"

    t = load("test.csv")
    t = t[t.scheme == "user"]
    med = t.groupby("model")[["ndcg@10", "recall@10", "auc", "coverage"]].median()
    for m, r in med.iterrows():
        v[f"test.{m}.ndcg"], v[f"test.{m}.recall"] = f4(r["ndcg@10"]), f4(r["recall@10"])
        v[f"test.{m}.coverage"] = pct(r["coverage"])
    v["test.users"] = f"{int(t.n_users.iloc[0]):,}"
    v["test.coverage_denominator"] = f"{int(t.coverage_denominator.iloc[0]):,}"
    rc = t[t.model == "two_stage"][["recall_ceiling@200"]].median().iloc[0]
    v["test.recall_ceiling_200"] = pct(rc)
    v["test.coverage_ratio.two_tower.ease"] = f"{med.loc['two_tower', 'coverage'] / med.loc['ease', 'coverage']:.1f}"
    gain = lambda m: med.loc[m, "ndcg@10"] - med.loc["two_tower", "ndcg@10"]
    v["ablation.no_ease_share"] = pct(gain("two_stage_no_ease") / gain("two_stage"), 0)

    g = load("test_gaps.csv")
    for r in g.itertuples():
        k = f"gap.{r.a}.{r.b}.{r.metric.split('@')[0]}"
        v[f"{k}.diff"], v[f"{k}.rel"] = sgn(r.diff), f"{100 * r.rel_diff:+.1f}%"
        v[f"{k}.ci"] = f"[{sgn(r.ci_low)}, {sgn(r.ci_high)}]"

    chain = ["two_stage", "two_tower", "ease", "implicit_als", "item_knn", "most_popular"]
    nd = g[g.metric == "ndcg@10"].set_index(["a", "b"])
    unclear = [f"{a} vs {b}" for a, b in zip(chain, chain[1:]) if not nd.loc[(a, b), "ci_low"] > 0]
    v["gaps.chain"] = (" > ".join(NAMES[m].strip("*") for m in chain) + ": every step is statistically clear"
                       if not unclear else "not every step is clear (" + ", ".join(unclear) + ")")

    st = load("predictions_status.csv").set_index("id")
    v["predictions.confirmed"] = str(int((st.verdict == "confirmed").sum()))
    v["predictions.refuted"] = str(int((st.verdict == "refuted").sum()))
    v["predictions.total"] = str(len(st))
    words = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
    for k in ("confirmed", "refuted", "total"):
        n = int(v[f"predictions.{k}"])
        v[f"predictions.{k}_word"] = words[n] if n < len(words) else str(n)
        v[f"predictions.{k}_Word"] = v[f"predictions.{k}_word"].capitalize()

    sc = load("split_comparison.csv").set_index("scheme")
    for s, r in sc.iterrows():
        v[f"split.{s}.ndcg"], v[f"split.{s}.users"] = f4(r["ndcg@10"]), f"{int(r.n_users):,}"
    v["split.ratio"] = f"{sc.loc['random', 'ratio_vs_global']:.2f}"
    v["split.global_cutoff_date"] = pd.to_datetime(int(num(("global", "t90_timestamp"))), unit="s").strftime("%B %Y")
    v["split.ratio_ci"] = f"{sc.loc['random', 'ratio_ci_low']:.2f}–{sc.loc['random', 'ratio_ci_high']:.2f}"

    tb = load("analysis/test_by_boundary.csv").set_index(["model", "boundary"])
    for (m, b), r in tb.iterrows():
        v[f"boundary.{m}.{b}"] = f4(r["ndcg@10"])
    for b in ("same_second", "within_1h", "over_1h"):
        v[f"boundary.share.{b}"] = pct(tb.loc[("ease", b), "users"] / tb.loc[("ease", "all"), "users"])

    p6 = stat_table("latency_prediction6.csv")
    v["latency.p6.p50"], v["latency.p6.p99"] = (f"{float(p6[('two_stage', k)]):.1f}"
                                                for k in ("client_p50_ms", "client_p99_ms"))
    v["latency.p6.p99_miss"] = f"{float(p6[('two_stage', 'client_p99_ms')]) - 25:.1f}"
    v["latency.p6.requests"] = f"{int(float(p6[('setup', 'requests_two_stage')])):,}"
    lt = load("latency_threads.csv")
    one, dflt = lt[lt.server_threads.astype(str) == "1"], lt[lt.server_threads.astype(str) == "default"]
    v["latency.threads1.p50"] = f"{one.client_p50_ms.median():.1f}"
    v["latency.threads1.p99_range"] = f"{one.client_p99_ms.min():.1f}–{one.client_p99_ms.max():.1f}"
    v["latency.default.p99_range"] = f"{dflt.client_p99_ms.min():.0f}–{dflt.client_p99_ms.max():.0f}"
    cur = stat_table("latency.csv")
    v["latency.fallback.p50"] = f"{float(cur[('popularity_fallback', 'client_p50_ms')]):.1f}"
    v["latency.load_s"] = f"{float(cur[('setup', 'model_load_seconds')]):.0f}"
    sp = load("serving_parity.csv").set_index("check").value
    v["parity.users"] = f"{int(float(sp['users_checked'])):,}"
    v["parity.top10"] = pct(float(sp["top10_identical_share"]), 0)

    pl = load("publish_log.csv")
    rej = pl[pl.decision == "reject"].iloc[-1]
    v["airflow.candidate"], v["airflow.live"] = f"{rej['candidate_val_ndcg@10']:.4f}", f"{rej['live_val_ndcg@10']:.4f}"
    v["airflow.epochs"] = str(int(rej.epochs))
    pe = load("pit_experiment.csv")
    pm = pe.groupby("variant")[["ndcg@10", "ndcg_diff_vs_headline", "ci_low", "ci_high"]].median()
    for var in ("headline", "pit", "pit_time"):
        v[f"pit.{var}.ndcg"] = f4(pm.loc[var, "ndcg@10"])
    for var in ("pit", "pit_time"):
        v[f"pit.{var}.diff"] = sgn(pm.loc[var, "ndcg_diff_vs_headline"])
        v[f"pit.{var}.ci"] = f"[{sgn(pm.loc[var, 'ci_low'])}, {sgn(pm.loc[var, 'ci_high'])}]"
    ps = load("publish_log_sandbox.csv")
    pub = ps[ps.decision == "publish"].iloc[-1]
    v["airflow.pub.candidate"], v["airflow.pub.live"] = (f"{pub['candidate_val_ndcg@10']:.4f}",
                                                          f"{pub['live_val_ndcg@10']:.4f}")
    v["airflow.margin"] = re.search(r"margin ([\d.]+)", pub.reason).group(1)

    bm = load("benchmark.csv").set_index(["size", "engine"])
    for (s, e), r in bm.iterrows():
        v[f"bench.{s}.{e}.with"], v[f"bench.{s}.{e}.warm"] = f"{r.with_startup_s:.1f}", f"{r.warm_compute_s:.1f}"
    br = load("benchmark_runs.csv")
    v["bench.runs"], v["bench.max_load"] = str(len(br)), f"{br.loadavg_1m_before.max():.1f}"

    for f, model in (("baselines.csv", "ease"), ("two_tower.csv", "two_tower"), ("two_stage.csv", "two_stage")):
        d = load(f)
        d = d[d.model == model]
        v[f"val.{model}.ndcg"] = f4(d["ndcg@10"].median())
    return v


# ---------------------------------------------------------------------------------------------
# Claims: prose statements in the template that depend on the data. If a result changes so a
# claim no longer holds, rendering fails instead of silently publishing a false sentence.
# ---------------------------------------------------------------------------------------------

def check_claims():
    tb = load("analysis/test_by_boundary.csv").set_index(["model", "boundary"])["ndcg@10"]
    bm = load("benchmark.csv").set_index(["size", "engine"])
    claims = {
        "two-tower beats EASE within a session":
            tb[("two_tower", "same_second")] > tb[("ease", "same_second")],
        "two-tower is worse than EASE when test starts > 1 h later":
            tb[("two_tower", "over_1h")] < tb[("ease", "over_1h")],
        "recent-10 EASE doesn't reproduce the two-tower's within-session score":
            tb[("ease_recent", "same_second")] < tb[("two_tower", "same_second")],
        "two-stage beats EASE in every boundary bucket":
            all(tb[("two_stage", b)] > tb[("ease", b)] for b in ("same_second", "within_1h", "over_1h", "all")),
        "DuckDB and Polars beat pandas and Spark at every size, both timings":
            all(bm.loc[(s, fast), col] < bm.loc[(s, slow), col]
                for s in ("1M", "5M", "25M") for fast in ("duckdb", "polars")
                for slow in ("pandas", "spark") for col in ("with_startup_s", "warm_compute_s")),
        "Spark wins at 25M, pandas at 1M and 5M (with startup)":
            bm.loc[("25M", "spark"), "with_startup_s"] < bm.loc[("25M", "pandas"), "with_startup_s"]
            and all(bm.loc[(s, "pandas"), "with_startup_s"] < bm.loc[(s, "spark"), "with_startup_s"]
                    for s in ("1M", "5M")),
    }
    g = load("test_gaps.csv").set_index(["a", "b", "metric"])
    claims["removing EASE features hurts the ranker significantly"] = \
        g.loc[("two_stage_no_ease", "two_stage", "ndcg@10"), "ci_high"] < 0
    claims["time features would help (so excluding them is a real cost)"] = \
        g.loc[("two_stage_with_time", "two_stage", "ndcg@10"), "ci_low"] > 0
    pe = load("pit_experiment.csv").groupby("variant")["ci_low"].median()
    claims["point-in-time features beat the headline's (both variants, CI above 0)"] = \
        pe["pit"] > 0 and pe["pit_time"] > 0
    false = [c for c, ok in claims.items() if not ok]
    if false:
        raise AssertionError(f"README claims no longer supported by results: {false}")


# ---------------------------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------------------------

def md(header, rows):
    esc = lambda x: str(x).replace("|", "\\|")
    return "\n".join(["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
                     + ["| " + " | ".join(esc(c) for c in r) + " |" for r in rows])


def build_tables():
    tb = {}
    t = load("test.csv")
    t = t[t.scheme == "user"]
    g = t.groupby("model")
    med = g[["ndcg@10", "recall@10", "auc", "coverage"]].median()
    seeds = g.seed.nunique()
    order = ["two_stage", "two_tower", "ease", "ease_recent", "implicit_als", "item_knn", "most_popular"]
    tb["headline"] = md(["Model", "NDCG@10", "Recall@10 (capped)", "AUC", "Coverage", "Runs"],
                        [[NAMES[m], f4(med.loc[m, "ndcg@10"]), f4(med.loc[m, "recall@10"]),
                          f3(med.loc[m, "auc"]), pct(med.loc[m, "coverage"]),
                          "3 (median)" if seeds[m] > 1 else "deterministic"] for m in order])
    abl = ["two_stage_with_time", "two_stage", "two_stage_no_ease", "two_tower"]
    gaps = load("test_gaps.csv")
    gap = lambda a, b: gaps[(gaps.a == a) & (gaps.b == b) & (gaps.metric == "ndcg@10")].iloc[0]
    def vs(m):
        if m == "two_stage":
            return "—"
        a, b, s = (m, "two_stage", 1) if m != "two_tower" else ("two_stage", "two_tower", -1)
        r = gap(a, b)
        lo, hi = sorted([s * r.ci_low, s * r.ci_high])
        return f"{sgn(s * r['diff'])} [{sgn(lo)}, {sgn(hi)}]"
    tb["ablation"] = md(["System (test)", "NDCG@10", "vs headline (95% CI)"],
                        [[NAMES[m], f4(med.loc[m, "ndcg@10"]), vs(m)] for m in abl])

    tbd = load("analysis/test_by_boundary.csv").set_index(["model", "boundary"])
    bmodels = ["ease", "ease_recent", "two_tower", "two_stage"]
    cols = [("same_second", "same second"), ("within_1h", "within 1 h"), ("over_1h", "over 1 h"), ("all", "all")]
    users = [f"{int(tbd.loc[('ease', b), 'users']):,}" for b, _ in cols]
    tb["boundary"] = md(["Test NDCG@10 by gap between last train/val rating and first test rating"]
                        + [f"{lbl} ({u} users)" for (b, lbl), u in zip(cols, users)],
                        [[NAMES[m]] + [f4(tbd.loc[(m, b), "ndcg@10"]) for b, _ in cols] for m in bmodels])

    sc = load("split_comparison.csv").set_index("scheme")
    lbl = {"random": "Random 80/10/10", "user": "Per-user time split (the project's)",
           "global": "Global time cutoff"}
    tb["splits"] = md(["Split (EASE, same config)", "Test users", "NDCG@10 (95% CI)", "× global"],
                      [[lbl[s], f"{int(sc.loc[s, 'n_users']):,}",
                        f"{f4(sc.loc[s, 'ndcg@10'])} ({f4(sc.loc[s, 'ndcg_ci_low'])}–{f4(sc.loc[s, 'ndcg_ci_high'])})",
                        f"{sc.loc[s, 'ratio_vs_global']:.2f}"] for s in ("random", "user", "global")])

    pr = load("predictions.csv").set_index("id")
    st = load("predictions_status.csv").set_index("id")
    mark = {"confirmed": "✅ confirmed", "refuted": "❌ refuted"}
    tb["predictions"] = md(["#", "Prediction (committed before training)", "Verdict", "Evidence"],
                           [[i, pr.loc[i, "prediction"], mark.get(st.loc[i, "verdict"], st.loc[i, "verdict"]),
                             st.loc[i, "evidence"]] for i in pr.index])

    bm = load("benchmark.csv").set_index(["size", "engine"])
    tb["benchmark"] = md(["Rows", "pandas", "Spark (6 cores)", "Polars", "DuckDB"],
                         [[f"{int(bm.loc[(s, 'pandas'), 'rows']):,}"] +
                          [f"{bm.loc[(s, e), 'with_startup_s']:.2f} / {bm.loc[(s, e), 'warm_compute_s']:.2f} s"
                           for e in ("pandas", "spark", "polars", "duckdb")] for s in ("1M", "5M", "25M")])

    rows = []
    for f in ("baselines.csv", "two_tower.csv", "two_stage.csv"):
        d = load(f)
        for m in d.model.unique():
            r = d[d.model == m]
            if m.startswith("two_stage_"):
                continue
            cfg = json.loads(r.config.iloc[0])
            cfg = {k: v for k, v in cfg.items() if k not in ("device", "features", "max_iter", "batch",
                                                                "hidden", "n_uniform", "strict_time")}
            trials = int(r.n_trials.iloc[0]) if "n_trials" in r and pd.notna(r.n_trials.iloc[0]) else "—"
            secs = r.tuning_seconds.iloc[0] if "tuning_seconds" in r else float("nan")
            hours = ("—" if pd.isna(secs) else f"{secs / 3600:.1f} h" if secs >= 3600
                     else f"{secs / 60:.0f} min" if secs >= 60 else f"{secs:.0f} s")
            rows.append([NAMES.get(m, m), f4(r["ndcg@10"].median()),
                         ", ".join(f"{k}={v}" for k, v in cfg.items()) or "—", trials, hours])
    tb["tuning"] = md(["Model", "Validation NDCG@10", "Chosen config", "Trials", "Tuning time"], rows)
    return tb


# ---------------------------------------------------------------------------------------------

def render(template_text):
    check_claims()
    values, tables = build_values(), build_tables()
    unknown = []

    def sub(m):
        key = m.group(1)
        if key.startswith("table:"):
            name = key[len("table:"):]
            if name in tables:
                return tables[name]
        elif key in values:
            return values[key]
        unknown.append(key)
        return m.group(0)

    out = PLACEHOLDER.sub(sub, template_text)
    if unknown:
        raise KeyError(f"unknown placeholders in {TEMPLATE.name}: {sorted(set(unknown))}")
    return HEADER + out


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    a = p.parse_args(argv)
    fresh = render(TEMPLATE.read_text())
    if a.check:
        current = README.read_text() if README.exists() else ""
        if current != fresh:
            diff = difflib.unified_diff(current.splitlines(), fresh.splitlines(),
                                        "README.md (committed)", "README.md (from results)", lineterm="", n=0)
            print("README.md is out of date with results/*.csv (run `make readme`):")
            print("\n".join(list(diff)[:60]))
            sys.exit(1)
        print("README.md matches results/*.csv")
        return
    README.write_text(fresh)
    print(f"wrote {README.name}")


if __name__ == "__main__":
    main()
